### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by jasonthane** [shanebdavis/caffeine-mc#2]
I'm getting an immediate error when running the caf command in a new repository (package.json below):

/Volumes/Storage/Active Projects/cas-corporate-metadata/node_modules/art-class-system/build/index.js:1189
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
                                                                                                                                                                                               ^

TypeError: Cannot read property 'prototype' of undefined
    at extend (/Volumes/Storage/Active Projects/cas-corporate-metadata/node_modules/art-class-system/build/index.js:1189:192)
    at /Volumes/Storage/Active Projects/cas-corporate-metadata/node_modules/art-class-system/build/index.js:1193:3
    at Object.module.exports.module.exports.author (/Volumes/Storage/Active Projects/cas-corporate-metadata/node_modules/art-class-system/build/index.js:1203:3)

package.json follows:
```
{
  "name": "touchpoint-reg-data",
  "version": "0.0.1",
  "description": "Convert Touchpoint registration and Buzzies Challenge data from JSON to CSV. Maybe correlate it while we're at it.",
  "main": "main.js",
  "keywords": [
    "General UI",
    "GenUI"
  ],
  "author": "Jason Thane",
  "license": "All rights reserved.",
  "dependencies": {
    "art-build-configurator": "^1.8.1",
    "art-class-system": "^1.0.1",
    "art-config": "^1.0.0",
    "art-standard-lib": "^1.0.0",
    "art-suite": "git://github.com/imikimi/art-suite",
    "art-testbench": "^1.0.0",
    "caffeine-script": "^0.38.1",
    "case-sensitive-paths-webpack-plugin": "^1.1.4",
    "coffee-loader": "^0.7.2",
    "coffee-script": "^1.12.3",
    "colors": "^1.1.2",
    "css-loader": "^0.26.1",
    "json-loader": "^0.5.4",
    "neptune-namespaces": "^1.9.1",
    "script-loader": "^0.7.0",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0",
    "webpack-merge": "^3.0.0"
  },
  "scripts": {}
}
```

**Comment by shanebdavis** [comment]
I just fixed something related to this. Try again? Fresh npm  install.

**Comment by jasonthane** [comment]
Still having this issue. Here are some concise repro steps:

```
--------------- jason@gozer Sat Jul 15 10:51 AM ---------------
14 ~/proj/touchpoint-reg-data :)  nano package.json
--------------- jason@gozer Sat Jul 15 10:53 AM ---------------
15 ~/proj/touchpoint-reg-data :) dir

total 2012
drwxr-xr-x@   3 jason  staff      374 Jul 15 10:49 .
drwxr-xr-x   22 jason  staff      782 Jul 13 13:48 ..
-rw-r--r--@   1 jason  staff   242762 Jul 12 16:43 6b29969f1eec_buzzie_challenge.json
-rw-r--r--@   1 jason  staff    75491 Jul 13 14:13 buzzies_challenge_2017-06-12.csv
-rw-r--r--@   1 jason  staff  1111828 Jul 12 16:27 ec3c8a608d07_user_registrations.json
drwxr-xr-x  545 jason  staff    18530 Jul 15 10:49 node_modules
-rw-r--r--    1 jason  staff   163312 Jul 15 10:49 package-lock.json
-rw-r--r--    1 jason  staff     1104 Jul 15 10:53 package.json
-rw-r--r--@   1 jason  staff      581 Jul 13 14:13 parseChallenges.js
-rw-r--r--@   1 jason  staff      583 Jul 13 14:11 parseRegistrations.js
-rw-r--r--@   1 jason  staff   442855 Jul 13 14:11 user_registrations_2017-06-12.csv
--------------- jason@gozer Sat Jul 15 10:53 AM ---------------
16 ~/proj/touchpoint-reg-data :) rm -rf node_modules
--------------- jason@gozer Sat Jul 15 10:54 AM ---------------
18 ~/proj/touchpoint-reg-data :) rm package-lock.json
--------------- jason@gozer Sat Jul 15 10:54 AM ---------------
19 ~/proj/touchpoint-reg-data :) npm install
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support

> fsevents@1.1.2 install /Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/fsevents
> node install

[fsevents] Success: "/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN touchpoint-reg-data@0.0.1 No repository field.
npm WARN touchpoint-reg-data@0.0.1 license should be a valid SPDX license expression

added 834 packages in 25.419s
--------------- jason@gozer Sat Jul 15 10:54 AM ---------------
20 ~/proj/touchpoint-reg-data :) caf
/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:115
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
                                                                                                                                                                                               ^

TypeError: Cannot read property 'prototype' of undefined
    at extend (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:115:192)
    at /Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:119:3
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:129:3)
    at __webpack_require__ (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:21:30)
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:1330:18)
    at __webpack_require__ (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:21:30)
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:1838:20)
    at __webpack_require__ (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:21:30)
    at /Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:67:18
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/build/caf-command.js:70:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/caf.js:3:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/caffeine-mc/caf:3:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

--------------- jason@gozer Sat Jul 15 10:55 AM ---------------
21 ~/proj/touchpoint-reg-data :) which caf
caf is ./node_modules/.bin/caf

**Comment by jasonthane** [comment]
And here's the package.json from the above attempt.

```
--------------- jason@gozer Sat Jul 15 10:55 AM ---------------
22 ~/proj/touchpoint-reg-data :) cat package.json
{
  "name": "touchpoint-reg-data",
  "version": "0.0.1",
  "description": "Convert Touchpoint registration and Buzzies Challenge data from JSON to CSV. Maybe correlate it while we're at it.",
  "main": "main.js",
  "keywords": [
    "General UI",
    "GenUI"
  ],
  "author": "Jason Thane",
  "license": "All rights reserved.",
  "dependencies": {
    "art-build-configurator": "^1.8.1",
    "art-class-system": "^1.0.1",
    "art-config": "^1.0.0",
    "art-standard-lib": "^1.0.0",
    "art-suite": "git://github.com/imikimi/art-suite",
    "art-testbench": "^1.0.0",
    "caffeine-mc": "^2.4.7",
    "caffeine-script": "^0.38.1",
    "case-sensitive-paths-webpack-plugin": "^1.1.4",
    "coffee-loader": "^0.7.2",
    "coffee-script": "^1.12.3",
    "colors": "^1.1.2",
    "css-loader": "^0.26.1",
    "fs-readfile-promise": "^3.0.0",
    "json-loader": "^0.5.4",
    "neptune-namespaces": "^1.9.1",
    "script-loader": "^0.7.0",
    "style-loader": "^0.13.1",
    "util": "^0.10.3",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0",
    "webpack-merge": "^3.0.0"
  },
  "scripts": {}
}
```

**Comment by jasonthane** [comment]
The package.json file is still not working, but I don't need what's in it, anyway. The following works:

```
--------------- jason@gozer Sat Jul 15 11:01 AM ---------------
39 ~/proj/touchpoint-reg-data :) rm -rf node_modules
--------------- jason@gozer Sat Jul 15 11:01 AM ---------------
40 ~/proj/touchpoint-reg-data :) npm install caffeine-mc

> fsevents@1.1.2 install /Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/fsevents
> node install

[fsevents] Success: "/Volumes/Storage/Active Projects/touchpoint-reg-data/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN touchpoint-reg-data@0.0.1 No repository field.
npm WARN touchpoint-reg-data@0.0.1 license should be a valid SPDX license expression

+ caffeine-mc@2.4.7
added 694 packages in 16.751s
--------------- jason@gozer Sat Jul 15 11:01 AM ---------------
41 ~/proj/touchpoint-reg-data :) caf 
Welcome to the CaffeineMC console.
For help: .help
Your current compiler is: CaffeineScript
caf-mc:CaffeineScript> 
```

**Comment by jasonthane** [comment]
So, I think you can close the issue. Sorry for the false alarm! If I get good repro steps on the other package.json that seems to indicate a bug, I will let you know.
